core:
  app_name: ""
  port: 8080
  env: "dev" # dev / stage / prod
  secret_key:

datasource:
  username: ""
  password: ""
  address: ""
  dbname: ""

redis:
  username: ""
  password: ""
  address: ""
  dbname: 0