// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/knight7024/go-push-server/ent/runtime.go

const (
	Version = "v0.11.2-0.20220805114204-0066eb986dd3"           // Version of ent codegen.
	Sum     = "h1:JNVBOLEDn2snBII7sjINt0AWn8WOwCdw4wNjW0J3px8=" // Sum of ent codegen.
)
